$p = "d:\data pribadi\project\TrahPanembahanSenopati\patrapsenopati\resources\js\Pages\trah\AdminShow.tsx"
Add-Content -Path $p -Value '                        <div className="px-8 py-2">'
Add-Content -Path $p -Value '                            <p className="text-center text-[11px] italic tracking-wide text-[#5c4a1e]">Mangasah Mingising Budi - Memasuh Malaning Bhumi - Memayu Hayuning Bawana</p>'
Add-Content -Path $p -Value '                        </div>'
Add-Content -Path $p -Value '                        <div className="flex justify-center px-8 pb-4 pt-2">'
Add-Content -Path $p -Value '                            {member?.foto ? ('
Add-Content -Path $p -Value '                                <img src={`/storage/${member.foto}`} alt="Foto" className="h-32 w-32 rounded-lg border-2 border-[#b08942] object-cover shadow-md" />'
Add-Content -Path $p -Value '                            ) : fotoPanembahan ? ('
Add-Content -Path $p -Value '                                <img src={fotoPanembahan} alt="Foto" className="h-32 w-32 rounded-lg border-2 border-[#b08942] object-cover shadow-md" />'
Add-Content -Path $p -Value '                            ) : ('
Add-Content -Path $p -Value '                                <div className="flex h-32 w-32 items-center justify-center rounded-lg border-2 border-[#b08942] bg-gray-200">'
Add-Content -Path $p -Value '                                    <span className="text-4xl text-gray-400">👤</span>'
Add-Content -Path $p -Value '                                </div>'
Add-Content -Path $p -Value '                            )}'
Add-Content -Path $p -Value '                        </div>'
Add-Content -Path $p -Value '                        <div className="border-t-2 border-[#b08942] bg-gradient-to-b from-white to-amber-50 px-8 py-4">'
Add-Content -Path $p -Value '                            <div className="space-y-2">'
Add-Content -Path $p -Value '                                {allFields.map((field, index) => ('
Add-Content -Path $p -Value '                                    <div key={index} className={`flex items-start ${field.isHighlight ? "font-bold text-green-800" : ""}`}>'
Add-Content -Path $p -Value '                                        <div className="w-48 flex-shrink-0 text-right pr-4">'
Add-Content -Path $p -Value '                                            <span className={`text-sm font-bold tracking-wide ${field.isHighlight ? "text-green-800" : "text-black"}`}>{field.label}: </span>'
Add-Content -Path $p -Value '                                        </div>'
Add-Content -Path $p -Value '                                        <div className="flex-1 text-sm text-gray-800">'
Add-Content -Path $p -Value '                                            {field.value || <span className="text-gray-400 italic">-</span>}'
Add-Content -Path $p -Value '                                        </div>'
Add-Content -Path $p -Value '                                    </div>'
Add-Content -Path $p -Value '                                ))}'
Add-Content -Path $p -Value '                            </div>'
Add-Content -Path $p -Value '                        </div>'
Add-Content -Path $p -Value '                        <div className="flex justify-end px-8 py-6">'
Add-Content -Path $p -Value '                            <div className="text-center">'
Add-Content -Path $p -Value '                                <p className="text-xs italic text-gray-600">Karangpandhan,</p>'
Add-Content -Path $p -Value '                                <div className="relative my-1 flex h-24 items-center justify-center">'
Add-Content -Path $p -Value '                                    {stempelUrl && ('
Add-Content -Path $p -Value '                                        <img src={stempelUrl} alt="Stempel" className="pointer-events-none absolute top-[-15px] left-[-15px] z-10 h-28 w-28 object-contain opacity-90 mix-blend-multiply" />'
Add-Content -Path $p -Value '                                    )}'
Add-Content -Path $p -Value '                                    {ttdUrl && ('
Add-Content -Path $p -Value '                                        <img src={ttdUrl} alt="TTD" className="pointer-events-none absolute z-25 h-20 w-32 object-contain mix-blend-multiply brightness-105 contrast-125 filter" />'
Add-Content -Path $p -Value '                                    )}'
Add-Content -Path $p -Value '                                </div>'
Add-Content -Path $p -Value '                                <div className="mt-1">'
Add-Content -Path $p -Value '                                    <span className="inline-block border-b border-black px-1 text-sm font-medium whitespace-nowrap text-gray-900">{namaTtd}</span>'
Add-Content -Path $p -Value '                                </div>'
Add-Content -Path $p -Value '                            </div>'
Add-Content -Path $p -Value '                        </div>'
Write-Host "Part 3 done"