$p = "d:\data pribadi\project\TrahPanembahanSenopati\patrapsenopati\resources\js\Pages\trah\AdminShow.tsx"
Add-Content -Path $p -Value ""
Add-Content -Path $p -Value "    return ("
Add-Content -Path $p -Value '        <AppLayout>'
Add-Content -Path $p -Value '            <Head title="Directory Book - PATRAP SENOPATI" />'
Add-Content -Path $p -Value '            <div className="mx-auto max-w-4xl p-4">'
Add-Content -Path $p -Value '                <Card className="overflow-hidden border border-gray-300 bg-white shadow-xl">'
Add-Content -Path $p -Value '                    <CardContent className="p-0 text-black">'
Add-Content -Path $p -Value '                        <div className="relative px-8 pt-6 pb-4">'
Add-Content -Path $p -Value '                            <div className="flex items-center justify-center">'
Add-Content -Path $p -Value '                                <div className="absolute top-4 left-8">'
Add-Content -Path $p -Value '                                    {logoUrl ? ('
Add-Content -Path $p -Value '                                        <img src={logoUrl} alt="Logo" className="h-24 w-24 object-contain" />'
Add-Content -Path $p -Value '                                    ) : ('
Add-Content -Path $p -Value '                                        <div className="flex h-24 w-24 items-center justify-center rounded-full border-2 border-yellow-500 bg-green-800">'
Add-Content -Path $p -Value '                                            <span className="text-xs font-bold text-yellow-400">LOGO</span>'
Add-Content -Path $p -Value '                                        </div>'
Add-Content -Path $p -Value '                                    )}'
Add-Content -Path $p -Value '                                </div>'
Add-Content -Path $p -Value '                                <div className="pl-16 text-center">'
Add-Content -Path $p -Value '                                    <h1 className="font-serif text-xl leading-tight tracking-[0.20em] text-[#1b3e2b]">TEDHAK TURUN</h1>'
Add-Content -Path $p -Value '                                    <h1 className="font-serif text-2xl font-bold leading-tight tracking-[0.20em] text-[#1b3e2b]">PANEMBAHAN SENOPATI</h1>'
Add-Content -Path $p -Value '                                    <div className="my-1 h-[2px] w-full bg-[#b08942]"></div>'
Add-Content -Path $p -Value '                                    <h2 className="font-serif text-2xl font-bold italic tracking-[0.25em] text-black">PATRAP SENOPATI</h2>'
Add-Content -Path $p -Value '                                    <p className="text-xs tracking-wider text-gray-600">(PAGUYUBAN TRAH PANEMBAHAN SENOPATI)</p>'
Add-Content -Path $p -Value '                                </div>'
Add-Content -Path $p -Value '                            </div>'
Add-Content -Path $p -Value '                        </div>'
Write-Host "Part 2 done"