$p = "d:\data pribadi\project\TrahPanembahanSenopati\patrapsenopati\resources\js\Pages\trah\AdminShow.tsx"
$lines = @(
    "import { Button } from '@/components/ui/button';",
    "import { Card, CardContent } from '@/components/ui/card';",
    "import AppLayout from '@/layouts/app-layout';",
    "import { Head, Link } from '@inertiajs/react';",
    "import { ArrowLeft, Download, FileText } from 'lucide-react';",
    "",
    "export default function TrahAdminShow({ member, settings }: { member: any; settings: any }) {",
    "    const logoUrl = settings?.logoUrl || null;",
    "    const stempelUrl = settings?.stempelUrl || null;",
    "    const ttdUrl = settings?.ttdUrl || null;",
    "    const namaTtd = settings?.namaTtd || 'R. Bigar Rahasia Siswa, S.Pd., M.Pd.B.I';",
    "    const qrUrl = settings?.qrUrl || null;",
    "    const fotoPanembahan = settings?.fotoPanembahan || null;",
    "",
    "    const allFields = [",
    "        { label: 'NO. REGISTRASI', value: member?.no_registrasi },",
    "        { label: 'TRAH TUMERAH', value: member?.trah_tumerah },",
    "        { label: 'MENYA-MENYA', value: member?.menya_menya },",
    "        { label: 'MENYAMAN', value: member?.menyaman },",
    "        { label: 'AMPLENG', value: member?.ampleng },",
    "        { label: 'CUMPLENG', value: member?.cumpleng },",
    "        { label: 'GIYENG', value: member?.giyeng },",
    "        { label: 'CENDHENG', value: member?.cendheng },",
    "        { label: 'GROPAK WATON', value: member?.gropak_waton },",
    "        { label: 'GALIH ASEM', value: member?.galih_asem },",
    "        { label: 'DEBOK BOSOK', value: member?.debok_bosok },",
    "        { label: 'GROPAK SENTHE', value: member?.gropak_senthe },",
    "        { label: 'GANTUNG SIWUR', value: member?.gantung_siwur },",
    "        { label: 'UDHEG-UDHEG', value: member?.udheg_udheg },",
    "        { label: 'WARENG', value: member?.wareng },",
    "        { label: 'CANGGAH', value: member?.canggah },",
    "        { label: 'BUYUT', value: member?.buyut },",
    "        { label: 'SIMBAH / EYANG', value: member?.simbah_eyang },",
    "        { label: 'BAPAK / IBU', value: member?.bapak_ibu },",
    "        { label: 'NAMA ANDA', value: member?.nama_anda, isHighlight: true },",
    "        { label: 'TEMPAT, TANGGAL LAHIR', value: member?.tempat_tanggal_lahir },",
    "        { label: 'ALAMAT', value: member?.alamat },",
    "    ];"
)
$lines | Set-Content $p
Write-Host "Part 1 done"