<?php

use App\Http\Controllers\GuestRegisterController;
use App\Http\Controllers\Auth\AuthenticatedSessionController;
use App\Http\Controllers\MenuController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\BackupController;
use App\Http\Controllers\AuditLogController;
use App\Http\Controllers\UserFileController;
use App\Http\Controllers\PermissionController;
use App\Http\Controllers\SettingAppController;
use App\Http\Controllers\MediaFolderController;
use App\Http\Controllers\DashboardUserController;
use App\Http\Controllers\FaceVerificationController;
use App\Http\Controllers\FaceRegisterController;
use App\Http\Controllers\EventController;
use App\Http\Controllers\WaSettingController;
use App\Http\Controllers\TamuController;
use App\Http\Controllers\HadiahController;
use App\Http\Controllers\SouvenirController;
use App\Http\Controllers\MejaController;
use App\Http\Controllers\GrupController;
use App\Http\Controllers\PertanyaanController;
use App\Http\Controllers\GuestSettingController;
use App\Http\Controllers\CheckInController;
use App\Http\Controllers\GuestDashboardPageController;
use App\Http\Controllers\BroadcastController;
use App\Http\Controllers\QrCodeController;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Redirect;

Route::get("/", fn() => Redirect::to("/dashboard"))->name("home");

Route::withoutMiddleware([\Illuminate\Foundation\Http\Middleware\VerifyCsrfToken::class])->group(function () {
    Route::get("/register/{token}", [GuestRegisterController::class, "show"])->name("guest.register");
    Route::post("/guest/register/simpan", [GuestRegisterController::class, "store"])->name("guest.register.store");
    Route::post("/logout", [AuthenticatedSessionController::class, "destroy"])->name("logout");
    Route::post("/face-api/register", [FaceVerificationController::class, "registerFace"]);
    Route::get("/face-api/status", [FaceVerificationController::class, "checkFaceStatus"]);
    Route::delete("/face-api/delete", [FaceVerificationController::class, "deleteFace"]);
    Route::post("/wa-settings/test-connection", [WaSettingController::class, "testConnection"]);
    Route::post("/wa-settings/test-send", [WaSettingController::class, "testSend"]);
});

Route::middleware(["auth"])->group(function () {
    Route::get("/dashboard", [DashboardUserController::class, "index"])->name("dashboard");
    Route::get("/menus", [MenuController::class, "index"])->name("menus.index");
    Route::get("/menus/create", [MenuController::class, "create"])->name("menus.create");
    Route::post("/menus", [MenuController::class, "store"])->name("menus.store");
    Route::get("/menus/{menu}/edit", [MenuController::class, "edit"])->name("menus.edit");
    Route::put("/menus/{menu}", [MenuController::class, "update"])->name("menus.update");
    Route::delete("/menus/{menu}", [MenuController::class, "destroy"])->name("menus.destroy");
    Route::post("/menus/reorder", [MenuController::class, "reorder"])->name("menus.reorder");
    Route::get("/users", [UserController::class, "index"])->name("users.index");
    Route::get("/users/create", [UserController::class, "create"])->name("users.create");
    Route::post("/users", [UserController::class, "store"])->name("users.store");
    Route::get("/users/{user}/edit", [UserController::class, "edit"])->name("users.edit");
    Route::put("/users/{user}", [UserController::class, "update"])->name("users.update");
    Route::delete("/users/{user}", [UserController::class, "destroy"])->name("users.destroy");
    Route::get("/roles", [RoleController::class, "index"])->name("roles.index");
    Route::get("/roles/create", [RoleController::class, "create"])->name("roles.create");
    Route::post("/roles", [RoleController::class, "store"])->name("roles.store");
    Route::get("/roles/{role}/edit", [RoleController::class, "edit"])->name("roles.edit");
    Route::put("/roles/{role}", [RoleController::class, "update"])->name("roles.update");
    Route::delete("/roles/{role}", [RoleController::class, "destroy"])->name("roles.destroy");
    Route::get("/permissions", [PermissionController::class, "index"])->name("permissions.index");
    Route::get("/permissions/create", [PermissionController::class, "create"])->name("permissions.create");
    Route::post("/permissions", [PermissionController::class, "store"])->name("permissions.store");
    Route::get("/permissions/{permission}/edit", [PermissionController::class, "edit"])->name("permissions.edit");
    Route::put("/permissions/{permission}", [PermissionController::class, "update"])->name("permissions.update");
    Route::delete("/permissions/{permission}", [PermissionController::class, "destroy"])->name("permissions.destroy");
    Route::get("/setting-app", [SettingAppController::class, "index"])->name("setting-app.index");
    Route::post("/setting-app", [SettingAppController::class, "update"])->name("setting-app.update");
    Route::post("/setting-app/upload", [SettingAppController::class, "upload"])->name("setting-app.upload");
    Route::get("/backups", [BackupController::class, "index"])->name("backups.index");
    Route::post("/backups", [BackupController::class, "store"])->name("backups.store");
    Route::get("/backups/download/{filename}", [BackupController::class, "download"])->name("backups.download");
    Route::delete("/backups/{filename}", [BackupController::class, "destroy"])->name("backups.destroy");
    Route::get("/audit-logs", [AuditLogController::class, "index"])->name("audit-logs.index");
    Route::get("/user-files", [UserFileController::class, "index"])->name("user-files.index");
    Route::post("/user-files", [UserFileController::class, "store"])->name("user-files.store");
    Route::delete("/user-files/{userFile}", [UserFileController::class, "destroy"])->name("user-files.destroy");
    Route::get("/media-folders", [MediaFolderController::class, "index"])->name("media-folders.index");
    Route::post("/media-folders", [MediaFolderController::class, "store"])->name("media-folders.store");
    Route::delete("/media-folders/{mediaFolder}", [MediaFolderController::class, "destroy"])->name("media-folders.destroy");
    Route::get("/events", [EventController::class, "index"])->name("events.index");
    Route::get("/events/create", [EventController::class, "create"])->name("events.create");
    Route::get("/events/{id}", [EventController::class, "show"])->name("events.show");
    Route::post("/events", [EventController::class, "store"])->name("events.store");
    Route::get("/events/{id}/edit", [EventController::class, "edit"])->name("events.edit");
    Route::put("/events/{id}", [EventController::class, "update"])->name("events.update");
    Route::delete("/events/{id}", [EventController::class, "destroy"])->name("events.destroy");
    Route::get("/wa-settings", [WaSettingController::class, "index"])->name("wa-settings.index");
    Route::post("/wa-settings", [WaSettingController::class, "store"])->name("wa-settings.store");
    Route::get("/broadcast", [BroadcastController::class, "index"])->name("broadcast.index");
    Route::post("/broadcast/send", [BroadcastController::class, "send"])->name("broadcast.send");
    Route::get("/qr", [QrCodeController::class, "index"])->name("qr.index");
    Route::post("/qr/generate-all", [QrCodeController::class, "generateAll"])->name("qr.generate-all");
    Route::get("/guest", [GuestDashboardPageController::class, "index"])->name("guest.dashboard");
    Route::get("/guest/tamu", [TamuController::class, "index"])->name("guest.tamu.index");
    Route::get("/guest/tamu/create", [TamuController::class, "create"])->name("guest.tamu.create");
    Route::post("/guest/tamu", [TamuController::class, "store"])->name("guest.tamu.store");
    Route::get("/guest/tamu/{tamu}/edit", [TamuController::class, "edit"])->name("guest.tamu.edit");
    Route::get("/guest/tamu/{tamu}", [TamuController::class, "show"])->name("guest.tamu.show");
    Route::put("/guest/tamu/{tamu}", [TamuController::class, "update"])->name("guest.tamu.update");
    Route::delete("/guest/tamu/{tamu}", [TamuController::class, "destroy"])->name("guest.tamu.destroy");
    Route::get("/guest/tamu/export", [TamuController::class, "export"])->name("guest.tamu.export");
    Route::post("/guest/tamu/import", [TamuController::class, "import"])->name("guest.tamu.import");
    Route::post("/guest/tamu/{tamu}/checkin", [CheckInController::class, "checkin"])->name("guest.tamu.checkin");
    Route::get("/guest/hadiah", [HadiahController::class, "index"])->name("guest.hadiah.index");
    Route::get("/guest/hadiah/create", [HadiahController::class, "create"])->name("guest.hadiah.create");
    Route::post("/guest/hadiah", [HadiahController::class, "store"])->name("guest.hadiah.store");
    Route::get("/guest/hadiah/{hadiah}/edit", [HadiahController::class, "edit"])->name("guest.hadiah.edit");
    Route::put("/guest/hadiah/{hadiah}", [HadiahController::class, "update"])->name("guest.hadiah.update");
    Route::delete("/guest/hadiah/{hadiah}", [HadiahController::class, "destroy"])->name("guest.hadiah.destroy");
    Route::get("/guest/souvenir", [SouvenirController::class, "index"])->name("guest.souvenir.index");
    Route::get("/guest/souvenir/create", [SouvenirController::class, "create"])->name("guest.souvenir.create");
    Route::post("/guest/souvenir", [SouvenirController::class, "store"])->name("guest.souvenir.store");
    Route::get("/guest/souvenir/{souvenir}/edit", [SouvenirController::class, "edit"])->name("guest.souvenir.edit");
    Route::put("/guest/souvenir/{souvenir}", [SouvenirController::class, "update"])->name("guest.souvenir.update");
    Route::delete("/guest/souvenir/{souvenir}", [SouvenirController::class, "destroy"])->name("guest.souvenir.destroy");
    Route::get("/guest/meja", [MejaController::class, "index"])->name("guest.meja.index");
    Route::get("/guest/meja/create", [MejaController::class, "create"])->name("guest.meja.create");
    Route::post("/guest/meja", [MejaController::class, "store"])->name("guest.meja.store");
    Route::get("/guest/meja/{meja}/edit", [MejaController::class, "edit"])->name("guest.meja.edit");
    Route::put("/guest/meja/{meja}", [MejaController::class, "update"])->name("guest.meja.update");
    Route::delete("/guest/meja/{meja}", [MejaController::class, "destroy"])->name("guest.meja.destroy");
    Route::post("/guest/meja/{meja}/assign", [MejaController::class, "assignTamu"])->name("guest.meja.assignTamu");
    Route::delete("/guest/meja-tamu/{mejaTamu}", [MejaController::class, "removeTamu"])->name("guest.meja.removeTamu");
    Route::get("/guest/grup", [GrupController::class, "index"])->name("guest.grup.index");
    Route::get("/guest/grup/create", [GrupController::class, "create"])->name("guest.grup.create");
    Route::post("/guest/grup", [GrupController::class, "store"])->name("guest.grup.store");
    Route::get("/guest/grup/{grup}/edit", [GrupController::class, "edit"])->name("guest.grup.edit");
    Route::put("/guest/grup/{grup}", [GrupController::class, "update"])->name("guest.grup.update");
    Route::delete("/guest/grup/{grup}", [GrupController::class, "destroy"])->name("guest.grup.destroy");
    Route::get("/guest/settings", [GuestSettingController::class, "edit"])->name("guest.settings");
    Route::post("/guest/settings", [GuestSettingController::class, "update"])->name("guest.settings.update");
    Route::get("/guest/pertanyaan", [PertanyaanController::class, "index"])->name("guest.pertanyaan.index");
    Route::get("/guest/pertanyaan/create", [PertanyaanController::class, "create"])->name("guest.pertanyaan.create");
    Route::post("/guest/pertanyaan", [PertanyaanController::class, "store"])->name("guest.pertanyaan.store");
    Route::get("/guest/pertanyaan/{pertanyaan}/edit", [PertanyaanController::class, "edit"])->name("guest.pertanyaan.edit");
    Route::put("/guest/pertanyaan/{pertanyaan}", [PertanyaanController::class, "update"])->name("guest.pertanyaan.update");
    Route::delete("/guest/pertanyaan/{pertanyaan}", [PertanyaanController::class, "destroy"])->name("guest.pertanyaan.destroy");
    Route::get("/checkin", [CheckInController::class, "index"])->name("checkin");
    Route::post("/checkin/{tamu}", [CheckInController::class, "checkin"])->name("checkin.store");
});

require __DIR__ . "/auth.php";

